name: Build and Release

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v7

            - name: Build
              run: cargo build --release

            - name: Package
              run: Compress-Archive -Path target/release/fourlight.exe, README.md, LICENSE -DestinationPath fourlight-windows-amd64.zip

            - uses: softprops/action-gh-release@v2
              with:
                  tag_name: build-${{ github.run_number }}
                  name: build-${{ github.run_number }}
                  files: fourlight-windows-amd64.zip
